import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { ClerkProvider } from "@clerk/nextjs";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import { ModalProvider } from "@/components/providers/modal-provider";
const font = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <ApolloWrapper>
        <html lang="en" suppressHydrationWarning>
          <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <ModalProvider/>
              <Toaster />
              {children}
            </ThemeProvider>
          </body>
        </html>
      </ApolloWrapper>
    </ClerkProvider>
  );
}





